FROM debian:stable-slim as builder

FROM python:3.9-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .

COPY app.py .
COPY homepage.html .
RUN pip install -r requirements.txt

#EXPOSE 5000
# command to run on container start
#CMD [ "python3", "./app.py" ]

CMD ["gunicorn", "--workers=2", "--chdir=.", "--bind", "0.0.0.0:5000", "--access-logfile=-", "--error-logfile=-", "app:app"]


