apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
      run: my-nginx
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: 1st
    image: <image-name> 
    #readinessProbe:
    #  httpGet:
    #  path: /healthz
    #  port: 8081
    #  initialDelaySeconds: 3
    #  timeoutSeconds: 3
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
